commands:
  fly: { enabled: true }
  god: { enabled: true }
  heal: { enabled: true }
  feed: { enabled: true }
  repair: { enabled: true }
  speed: { enabled: true }
  ext: { enabled: true }
  invsee: { enabled: true }
  ec: { enabled: true }
  top: { enabled: true }
  back: { enabled: true }
  hat: { enabled: true }
  anvil: { enabled: true }
  wb: { enabled: true }
  clear: { enabled: true }
  skull: { enabled: true }
  itemname: { enabled: true }
  lore: { enabled: true }
  sudo: { enabled: true }
  day: { enabled: true }
  night: { enabled: true }
  sun: { enabled: true }
  rain: { enabled: true }
  ping: { enabled: true }
  seen: { enabled: true }
  playtime: { enabled: true }
  broadcast: { enabled: true }
  clearchat: { enabled: true }
  gm: { enabled: true }
